name: ServerEconomyTracker
version: '1.0.1'
main: dev.zyverasystems.ServerEconomyTracker
api-version: '1.21'
authors: [ Zyvera-Systems, GrueneKatze ]
depend: [Vault]
softdepend:
  - Essentials
  - XConomy

commands:
  economytracker:
    description: Main Command
    usage: /economytracker
    aliases:
      - et

permissions:
  economytracker.stats:
    description: Shows you the stats about the economy
    default: true
  economytracker.reload:
    description: Reloading the plugin config and messages
    default: op